== Dokumentation

=== Beschreibung reverse engineered Webseitedaten

==== Abholdaten

https://trenntstadt-berlin.de/api-abfuhr.php?adrkey=6900000&amp;step=2

scheinbar sind die adrkeys die primärschlüssel.
Auf der Webseite wird eine Adresse zunächst in einen adrkey umgewandelt, mit dem dann angefragt wird.
Scheinbar werden die schlüssel bei neuen abholungen neu gesetzt und dann die alten Werte gelöscht

==== Adressauflösung

* Beispiel https://trenntstadt-berlin.de/api-abfuhr.php?str=karl-marx-alle&plz=1234&step=1
* str : Die Strasse
* plz : Postleitzahl der Strasse (optional)
* wird die plz weggelassen, werden alle strasen gefunden
* wird die strasse weggelassen werden alle strassen in einem stadtbezirk gefunden

=== Beschreibung der Dunmp Dateien

* Flache Textedatei
* encoding UTF8
* Format Strasse, Hausnummer, Servicetag, servicedate, primaerschluessel remote system, häufigkeit
* Delimeter: "::::" (keine Ahnung, was für kranke Tricks es bei den Adressen gibt)
* Wenn in der Datei adrkeys fehlen, dann wurden dafür keine Daten im Originalsystem geliefert